(* EMON Syntax Definition in EBNF (v1.1) *)

emon_document   = { comment | definition | record } ;

comment         = "//" , { ? any character except newline ? } ;

definition      = "#" , identifier , "(" , field_list , ")" , [ "[]" ] ;
field_list      = field , { "," , field } ;
field           = identifier , ":" , type ;

record          = "=" , value , { "," , value } ;

type            = "string" | "number" | "bool" | "boolean" | "float" | "int"
                | "[" , type , "]"
                | "#" , identifier
                | "(" , field_list , ")" ;

value           = string | number | boolean | null | object | array | multiline_string | reference ;

object          = "{" , [ value , { "," , value } ] , "}" ;
array           = "[" , [ value , { "," , value } ] , "]" ;

multiline_string = "\"\"\"" , { ? any character including newline ? } , "\"\"\"" ;

reference       = "#" , identifier ;

identifier      = letter , { letter | digit | "_" } ;
string          = '"' , { character } , '"' | unquoted_string ;
unquoted_string = letter , { letter | digit | "_" | "-" | "@" | "." } ;

number          = [ "-" ] , digit , { digit | "." , digit } ;
boolean         = "true" | "false" ;
null            = "null" ;

letter          = ? any alphabetic character ? ;
digit           = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
character       = ? any printable character except " and newline ? ;
